### ISSUE TITLE
Npe On Loading with new structure

### ISSUE THREAD

**Issue by DTS-MC** [DTS-MC/HeadShopAdvanced#2]
[19:39:45] [Server thread/INFO]: Starting Minecraft server on 192.168.1.154:25569
[19:39:45] [Server thread/INFO]: Using default channel type
[19:39:45] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[19:39:46] [Server thread/INFO]: [HeadShop] 2.1aHEADSHOP SCREAMS THE SIGNFILE IS NULL
[19:39:46] [Server thread/INFO]: [HeadShop] 2.1aHEADSHOP SCREAMS THE SIGNFILE CONFIG IS NULL
[19:39:46] [Server thread/INFO]: [HeadShop] 2.1asign Config Is Null! line 97 Main.java Class
[19:39:46] [Server thread/WARN]: java.lang.NullPointerException
[19:39:46] [Server thread/WARN]: 	at me.DaddyEric.HeadShopAdvanced.Main.loadYamls(Main.java:104)
[19:39:46] [Server thread/WARN]: 	at me.DaddyEric.HeadShopAdvanced.Handlers.SignHandler.getAllSigns(SignHandler.java:131)
[19:39:46] [Server thread/WARN]: 	at me.DaddyEric.HeadShopAdvanced.Handlers.SignHandler.loadSignsFromConfig(SignHandler.java:24)
[19:39:46] [Server thread/WARN]: 	at me.DaddyEric.HeadShopAdvanced.Handlers.SignHandler.<init>(SignHandler.java:20)
[19:39:46] [Server thread/WARN]: 	at me.DaddyEric.HeadShopAdvanced.Main.<init>(Main.java:34)
[19:39:46] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:39:46] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:39:46] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:39:46] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[19:39:46] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[19:39:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[19:39:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[19:39:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[19:39:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
[19:39:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292)
[19:39:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[19:39:46] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[19:39:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:39:46] [Server thread/ERROR]: Could not load 'plugins/HeadShop2.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at me.DaddyEric.HeadShopAdvanced.Handlers.SignHandler.getAllSigns(SignHandler.java:133) ~[?:?]
	at me.DaddyEric.HeadShopAdvanced.Handlers.SignHandler.loadSignsFromConfig(SignHandler.java:24) ~[?:?]
	at me.DaddyEric.HeadShopAdvanced.Handlers.SignHandler.<init>(SignHandler.java:20) ~[?:?]
	at me.DaddyEric.HeadShopAdvanced.Main.<init>(Main.java:34) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-76236cb-d4e32ce]
	... 6 more

**Comment by DTS-MC** [comment]
Fixed Was problem with initialization of SIgnHandler
